---
name: Run tests

on:  # yamllint disable-line rule:truthy
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out master
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Run tests
        run: |
          poetry install
          make test
